#!/usr/bin/env python3
"""
tools/pspdisasm/gen_vfpu_decode.py -- turn the manual-derived VFPU table into a C
decoder.

docs/vfpu_table.json is extracted page by page from
  document/hardware_manual/VFPU/VFPU-Instruction_Manual-English.pdf
by extract_vfpu.py: 267 forms, every bit accounted for. This makes that table
the decoder the runtime uses too, so decode is never re-derived by hand and
can never drift from the disassembler's.

Writes:
  generated/vfpu_ops.h    enum VfpuOp, one per form, plus vfpu_op_name()
  generated/vfpu_decode.c u32 -> VfpuOp

Longest-match order: forms are tried most-specific mask first, so a form with
a wider mask always wins over a more general one that also matches.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
DEFAULT_TABLE = ROOT / "data" / "vfpu_table.json"
DEFAULT_OUT = ROOT / "generated"


def c_ident(name: str) -> str:
    return "VOP_" + name.upper().replace(".", "_").replace("+", "P")


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--table", type=Path, default=DEFAULT_TABLE)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    a = ap.parse_args(argv)

    if not a.table.exists():
        print(f"error: {a.table} missing -- run extract_vfpu.py first",
              file=sys.stderr)
        return 2
    doc = json.loads(a.table.read_text(encoding="utf-8"))
    ins = doc["instructions"]

    seen: dict[str, dict] = {}
    for e in ins:
        seen.setdefault(e["name"], e)
    forms = sorted(seen.values(),
                   key=lambda e: (-bin(e["mask"]).count("1"), e["name"]))

    idents = [c_ident(e["name"]) for e in forms]
    dups = {i for i in idents if idents.count(i) > 1}
    if dups:
        print(f"error: C identifier collision: {sorted(dups)}", file=sys.stderr)
        return 1

    a.out.mkdir(parents=True, exist_ok=True)

    hdr = ["/* generated by tools/pspdisasm/gen_vfpu_decode.py -- do not edit",
           " *",
           f" * source: {doc.get('source', 'docs/vfpu_table.json')}",
           f" * {len(forms)} distinct VFPU forms",
           " */",
           "#ifndef PSPRECO_VFPU_OPS_H",
           "#define PSPRECO_VFPU_OPS_H",
           '#include "pspreco.h"',
           "",
           "typedef enum {",
           "    VOP_UNKNOWN = 0,"]
    hdr += [f"    {c_ident(e['name'])}," for e in forms]
    hdr += ["    VOP_COUNT",
            "} VfpuOp;",
            "",
            "VfpuOp      vfpu_decode(u32 word);",
            "const char *vfpu_op_name(VfpuOp op);",
            "",
            "#endif"]
    (a.out / "vfpu_ops.h").write_text("\n".join(hdr) + "\n", encoding="utf-8")

    rows = ",\n    ".join(
        f"{{ 0x{e['mask']:08x}u, 0x{e['match']:08x}u, {c_ident(e['name'])} }}"
        f"  /* {e['name']} */"
        for e in forms)
    names = ",\n    ".join(f'"{e["name"]}"' for e in forms)

    src = f'''/* generated by tools/pspdisasm/gen_vfpu_decode.py -- do not edit
 *
 * source: {doc.get('source', 'docs/vfpu_table.json')}
 */
#include "vfpu_ops.h"

typedef struct {{ u32 mask, match; VfpuOp op; }} VfpuForm;

/* Sorted most-specific mask first, so the longest match wins. */
static const VfpuForm g_forms[] = {{
    {rows}
}};
#define VFPU_FORM_COUNT ((unsigned)(sizeof g_forms / sizeof g_forms[0]))

static const char *const g_names[] = {{
    {names}
}};

VfpuOp vfpu_decode(u32 word)
{{
    unsigned i;
    for (i = 0; i < VFPU_FORM_COUNT; i++)
        if ((word & g_forms[i].mask) == g_forms[i].match)
            return g_forms[i].op;
    return VOP_UNKNOWN;
}}

const char *vfpu_op_name(VfpuOp op)
{{
    if (op <= VOP_UNKNOWN || op >= VOP_COUNT) return "?";
    return g_names[(unsigned)op - 1u];
}}
'''
    (a.out / "vfpu_decode.c").write_text(src, encoding="utf-8")
    print(f"wrote {a.out / 'vfpu_ops.h'} and {a.out / 'vfpu_decode.c'} "
          f"({len(forms)} forms)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
