#!/usr/bin/env python3
"""
tools/pspdisasm/vfpu.py -- VFPU decode/encode layer.

The instruction table is NOT hand-written: it is generated by
`extract_vfpu.py` straight out of the hardware manual
(document/hardware_manual/VFPU/VFPU-Instruction_Manual-English.pdf, one
instruction per page, each with its 31..0 bit diagram) into
docs/vfpu_table.json. Every entry therefore carries an `manual_ref` naming the
manual page it came from, satisfying RECOMP_PLAN §0.

Known limitation, deliberate and recorded in docs/ISA_COVERAGE.md: vector
register operands are printed in raw numeric form `v[N]` rather than the
manual's S###/C###/R###/M###/E### mnemonic syntax. The numeric form is
unambiguous and round-trips exactly; the human-readable naming (and the
vpfx*/prefix-stack state machine, which is a *semantic* concern for Phase 3,
not a decoding one) is follow-up work.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

TABLE_PATH = Path(__file__).resolve().parents[2] / "data" / "vfpu_table.json"


@dataclass(frozen=True)
class VField:
    name: str
    parts: tuple[tuple[int, int, int], ...]   # (shift, bits, dst_lsb)

    @property
    def mask(self) -> int:
        m = 0
        for shift, bits, _ in self.parts:
            m |= ((1 << bits) - 1) << shift
        return m

    @property
    def width(self) -> int:
        return max(lsb + bits for _, bits, lsb in self.parts)

    def extract(self, w: int) -> int:
        v = 0
        for shift, bits, lsb in self.parts:
            v |= ((w >> shift) & ((1 << bits) - 1)) << lsb
        return v

    def insert(self, v: int) -> int:
        w = 0
        for shift, bits, lsb in self.parts:
            w |= ((v >> lsb) & ((1 << bits) - 1)) << shift
        return w


@dataclass(frozen=True)
class VInsn:
    name: str
    mask: int
    match: int
    fields: tuple[VField, ...]
    operands: tuple[str, ...]     # rendering order; "" means fallback form
    manual_ref: str

    def field(self, name: str) -> VField | None:
        for f in self.fields:
            if f.name == name:
                return f
        return None


_OPTOK_RE = re.compile(r"^([A-Za-z]\w*)$")
_MEMTOK_RE = re.compile(r"^([A-Za-z]\w*)\(([A-Za-z]\w*)\)$")


def _load() -> list[VInsn]:
    if not TABLE_PATH.exists():
        return []
    raw = json.loads(TABLE_PATH.read_text(encoding="utf-8"))
    out: list[VInsn] = []
    for e in raw["instructions"]:
        fields = tuple(
            VField(name, tuple((p["shift"], p["bits"], p["dst_lsb"])
                               for p in sorted(parts, key=lambda x: x["dst_lsb"])))
            for name, parts in sorted(e["fields"].items())
        )
        names = {f.name for f in fields}

        # Operand order comes from the manual's own "Syntax:" line when every
        # field it names is a real field; otherwise we fall back to an explicit
        # `field=value` form, which is unambiguous and still round-trips.
        ops: list[str] = []
        covered: set[str] = set()
        syn = e.get("syntax", "")
        tail = syn.split(None, 1)[1] if len(syn.split(None, 1)) > 1 else ""
        for tok in (t.strip() for t in tail.split(",") if t.strip()):
            m = _MEMTOK_RE.match(tok)
            if m and m.group(1) in names and m.group(2) in names:
                ops.append(tok)
                covered |= {m.group(1), m.group(2)}
                continue
            m = _OPTOK_RE.match(tok)
            if m and m.group(1) in names:
                ops.append(tok)
                covered.add(m.group(1))
                continue
            ops = []
            break
        if covered != names:
            ops = []

        out.append(VInsn(e["name"], e["mask"], e["match"], fields,
                         tuple(ops), e.get("manual_ref", "")))
    # most-specific mask first
    out.sort(key=lambda i: bin(i.mask).count("1"), reverse=True)
    return out


TABLE: list[VInsn] = _load()
_BY_NAME = {i.name: i for i in TABLE}

GPR_FIELDS = {"rs", "rt", "rd", "base"}


def mnemonics() -> set[str]:
    return set(_BY_NAME)


def owns_mnemonic(m: str) -> bool:
    return m in _BY_NAME


def _sext(v: int, bits: int) -> int:
    return v - (1 << bits) if v & (1 << (bits - 1)) else v


def _render(insn: VInsn, f: VField, v: int) -> str:
    if f.name in GPR_FIELDS:
        from isa import GPR
        return "$" + GPR[v]
    if f.name == "offset":
        # The manual: "generated by ignoring the two low-order bits of the
        # 16-bit offset, sign-extending the remaining 14 bits" -- the encoded
        # field is offset>>2, so print the byte offset.
        return str(_sext(v, f.width) << 2)
    return f"v[{v}]" if f.name.startswith("v") else f"0x{v:x}"


def disassemble(word: int, pc: int) -> str | None:
    for insn in TABLE:
        if (word & insn.mask) != insn.match:
            continue
        if not insn.fields:
            return insn.name
        if insn.operands:
            parts: list[str] = []
            for tok in insn.operands:
                m = _MEMTOK_RE.match(tok)
                if m:
                    fo = insn.field(m.group(1))
                    fb = insn.field(m.group(2))
                    parts.append(f"{_render(insn, fo, fo.extract(word))}"
                                 f"({_render(insn, fb, fb.extract(word))})")
                else:
                    f = insn.field(tok)
                    parts.append(_render(insn, f, f.extract(word)))
            return f"{insn.name} {', '.join(parts)}"
        # fallback: explicit field=value, sorted by field name
        parts = [f"{f.name}=0x{f.extract(word):x}" for f in insn.fields]
        return f"{insn.name} {', '.join(parts)}"
    return None


_ASM_MEM_RE = re.compile(r"^(-?\d+)\((\$\w+)\)$")
_ASM_V_RE = re.compile(r"^v\[(\d+)\]$")
_ASM_KV_RE = re.compile(r"^(\w+)=(0x[0-9a-fA-F]+|\d+)$")


def _parse_value(insn: VInsn, f: VField, tok: str) -> int:
    if f.name in GPR_FIELDS:
        from isa import GPR_INDEX
        return GPR_INDEX[tok.lstrip("$")]
    if f.name == "offset":
        return (int(tok, 10) >> 2) & ((1 << f.width) - 1)
    m = _ASM_V_RE.match(tok)
    if m:
        return int(m.group(1))
    return int(tok, 0)


def assemble(text: str, pc: int) -> int:
    head, _, tail = text.strip().partition(" ")
    insn = _BY_NAME.get(head)
    if insn is None:
        raise ValueError(f"unknown VFPU mnemonic {head!r}")
    word = insn.match
    toks = [t.strip() for t in tail.split(",") if t.strip()]

    if not insn.fields:
        return word
    if insn.operands:
        for tok_spec, tok in zip(insn.operands, toks):
            m = _MEMTOK_RE.match(tok_spec)
            if m:
                mm = _ASM_MEM_RE.match(tok)
                if not mm:
                    raise ValueError(f"bad memory operand {tok!r}")
                fo = insn.field(m.group(1))
                fb = insn.field(m.group(2))
                word |= fo.insert(_parse_value(insn, fo, mm.group(1)))
                word |= fb.insert(_parse_value(insn, fb, mm.group(2)))
            else:
                f = insn.field(tok_spec)
                word |= f.insert(_parse_value(insn, f, tok))
        return word & 0xFFFFFFFF

    for tok in toks:
        m = _ASM_KV_RE.match(tok)
        if not m:
            raise ValueError(f"bad field assignment {tok!r}")
        f = insn.field(m.group(1))
        if f is None:
            raise ValueError(f"{head}: no field {m.group(1)!r}")
        word |= f.insert(int(m.group(2), 0))
    return word & 0xFFFFFFFF


def selftest() -> list[str]:
    """Every bit must be fixed by the mask or owned by exactly one field."""
    problems: list[str] = []
    for insn in TABLE:
        covered = insn.mask
        for f in insn.fields:
            if covered & f.mask:
                problems.append(f"{insn.name}: field {f.name} overlaps")
            covered |= f.mask
        if covered != 0xFFFFFFFF:
            problems.append(
                f"{insn.name}: bits {(~covered) & 0xFFFFFFFF:#010x} unaccounted "
                f"({insn.manual_ref})")
    return problems


if __name__ == "__main__":
    print(f"VFPU entries: {len(TABLE)}")
    p = selftest()
    print(f"bit coverage: {'OK' if not p else str(len(p)) + ' PROBLEMS'}")
    for x in p[:25]:
        print("   ", x)
    nofmt = [i.name for i in TABLE if i.fields and not i.operands]
    print(f"fallback field=value form: {len(nofmt)} -> {nofmt[:12]}")
